version: '3.8'

services:
  # Backend service
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    ports:
      - "8000:3000"  # Map host port 8000 to container port 3000
    volumes:
      - ./apps/backend:/app
    environment:
      - DEBUG=True
      - CORS_ORIGINS=["http://localhost:3000", "http://localhost:5173", "http://frontend:80"]
      - DYNAMODB_ENDPOINT_URL=http://dynamodb-local:8000
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
    depends_on:
      - dynamodb-local
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]  # Updated port in health check
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Frontend service
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Map host port 3000 to container port 80
    depends_on:
      - backend
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules

  # DynamoDB Local for development
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    ports:
      - "8001:8000"
    volumes:
      - dynamodb-data:/home/dynamodblocal/data
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    user: "root"  # Run as root to avoid permission issues

volumes:
  dynamodb-data:
